services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_generic
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_generic
    restart: always
    platform: linux/amd64
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql_db
      PMA_USER: root
      PMA_PASSWORD: rootpass
      UPLOAD_LIMIT: 128M
      MEMORY_LIMIT: 256M
      MAX_EXECUTION_TIME: 300
    depends_on:
      - mysql_db

volumes:
  mysql_data:
